apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-producer
  template:
    metadata:
      labels:
        app: demo-producer
    spec:
      containers:
      - name: demo-producer
        image: quay.io/strimzi/kafka:0.48.0-kafka-4.1.0
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting demo producer..."
          # Wait for Kafka to be ready
          until bin/kafka-topics.sh --bootstrap-server kafka-cluster-kafka-bootstrap:9092 --list | grep -q test-topic; do
            echo "Waiting for test-topic to be available..."
            sleep 5
          done
          
          echo "Topic is ready, starting to produce messages..."
          
          # Generate sample data
          counter=1
          while true; do
            timestamp=$(date '+%Y-%m-%d %H:%M:%S')
            message="{\"id\": $counter, \"timestamp\": \"$timestamp\", \"message\": \"Hello from Kafka demo producer\", \"data\": {\"value\": $((RANDOM % 100)), \"category\": \"demo\"}}"
            
            echo "$message" | bin/kafka-console-producer.sh \
              --bootstrap-server kafka-cluster-kafka-bootstrap:9092 \
              --topic test-topic
            
            echo "Produced message $counter at $timestamp"
            counter=$((counter + 1))
            sleep 10
          done
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
