apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: cluster-rebalance-add-broker
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  mode: add-brokers
  brokers: [3] 
